<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>
    <!-- <xacro:include filename="$(find rm_description)/urdf/common/omni_wheel.urdf.xacro"/> -->
    <xacro:include filename="$(find rm_description)/urdf/common/leg.urdf.xacro"/>
    <!-- <xacro:include filename="$(find rm_description)/urdf/balance/reaction_wheel.urdf.xacro"/> -->
    <!-- <xacro:include filename="$(find rm_description)/urdf/common/swerve_drive.urdf.xacro"/> -->
    
    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.4"/>
    <xacro:property name="wheel_base" value="0.4"/>
    <xacro:property name="leg_z_offset" value="-0.068374"/>
    <xacro:property name="wheel_offset_z" value="-0.068374"/>


    <xacro:macro name="chassis">

        <link name="base_link" >
            <inertial>
                <mass value="10.34269"/>  <!--连杆质量 -->
                <origin xyz="-0.003691 -0.001885 0.024404"/>  <!--质心相对于连杆坐标原点的位置。xyz属性分别指定了质心在x、y、z轴上的偏移量 -->
                <inertia ixx="1.952E-01" ixy="-1.504E-03" ixz="5.871E-03" iyy="3.011E-01"
                         iyz="-1.077E-03" izz="4.074E-01"/>  <!--惯性矩阵的三个主轴的惯性矩（ixx, iyy, izz）和惯性积（ixy, ixz, iyz）。惯性矩是质量分布的度量，惯性积表示质量分布的非对称性 -->
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 .001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/hero/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>


        <xacro:first_leg prefix="left_front" connected_to="base_link"
                            reflex="1"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"
                            mechanical_reduction="1"/>
        <xacro:second_leg prefix="left_front" connected_to="left_front_first_leg"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"/>

        <xacro:first_leg prefix="left_back" connected_to="base_link"
                            reflex="1"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"
                            mechanical_reduction="1"/>
        <xacro:second_leg prefix="left_back" connected_to="left_back_first_leg"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"/>

        <xacro:first_leg prefix="right_front" connected_to="base_link"
                            reflex="1"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"
                            mechanical_reduction="1"/>
        <xacro:second_leg prefix="right_front" connected_to="right_front_first_leg"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"/>

        <xacro:first_leg prefix="right_back" connected_to="base_link"
                            reflex="1"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"
                            mechanical_reduction="1"/>
        <xacro:second_leg prefix="right_back" connected_to="right_back_first_leg"
                            pitch_offset="0"
                            leg_x_offset="${wheel_base/2}"
                            leg_y_offset="${wheel_track/2}"
                            leg_z_offset="${leg_z_offset}"/>                  

        <xacro:mecanum_wheel prefix="left" connected_to="left_front_second_leg"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="simple"
                             max_effort="5" max_velocity="50"/>
        <xacro:mecanum_wheel prefix="right" connected_to="right_front_second_leg"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="simple"
                             max_effort="5" max_velocity="50"/>
        <xacro:wheel_transmission prefix="left" mechanical_reduction="1.0"/>
        <xacro:wheel_transmission prefix="right" mechanical_reduction="-1.0"/>


    </xacro:macro>

</robot>
