rm_hw:
  bus:
    - can0
    # - can1
    # - eno1
    # - 192.168.4.102
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  # Configurations of the actuators
  actuators:
    left_back_wheel_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 150
    left_front_wheel_motor:
      bus: can0
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 150  
    right_front_wheel_motor:
      bus: can0
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 150
    right_back_wheel_motor:
      bus: can0
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 150

    # mit_joint_motor:
    #   bus: can0
    #   id: 0x210
    #   type: rm_3508
    #   lp_cutoff_frequency: 150
    # joint1_motor:
    #   bus: can0
    #   id: 0x205
    #   type: rm_3508
    #   lp_cutoff_frequency: 150  
    # left_back_wheel_joint:
    #   bus: can0
    #   id: 0x206
    #   type: rm_3508
    #   lp_cutoff_frequency: 150
    # left_front_wheel_joint:
    #   bus: can0
    #   id: 0x207
    #   type: rm_3508
    #   lp_cutoff_frequency: 150  
    # right_back_wheel_joint:
    #   bus: can0
    #   id: 0x208
    #   type: rm_3508
    #   lp_cutoff_frequency: 150
    # left_front_pivot_motor:
    #   bus: can0
    #   id: 0x209
    #   type: rm_3508
    #   lp_cutoff_frequency: 150
  # imus:
  #   gimbal_imu:
  #     frame_id: gimbal_imu
  #     bus: can1
  #     id: 0x300
  #     orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
  #     angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
  #     linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
  #     angular_vel_coeff: 0.0010652644
  #     accel_coeff: 0.0017944335
  #     temp_coeff: 0.125
  #     temp_offset: 23.0
  #     filter: complementary
  #     do_bias_estimation: false
  #     do_adaptive_gain: true
  #     gain_acc: 0.0003
  # gpios:
  #   front_lamp:
  #     pin: 245
  #     direction: out
  #   back_lamp:
  #     pin: 246
  #     direction: out
